### ISSUE TITLE
Instructions for compiling on mac OSX (high sierra)

### ISSUE THREAD

**Issue by wildnrg** [valiant1x/intensecoin#11]
Having problems running cmake .. on mac osx high sierra.  Would appreciate some instructions for Mac OSX.  Thanks

I have boost installed and I can see libboost_thread-mt.dylib in /usr/local/opt/boost/lib/

-- Could NOT find Threads (missing: Threads_FOUND) 
CMake Error at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:1928 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.66.0

  Boost include path: /usr/local/include

  Could not find the following static Boost libraries:

          boost_thread (missing dependency: Threads)

**Comment by sebseb7** [comment]
check CMakeError.log

**Comment by valiant1x** [comment]
please provide the output of CMakeError.log as sebseb7 mentioned, and consider using an older version of Boost.

**Comment by cryptoluka** [comment]
Just delete this: -Werror
on daemon CMakelist.txt line 92
