### ISSUE TITLE
Deamon tx error

### ISSUE THREAD

**Issue by ddvs1** [valiant1x/intensecoin#12]
Hi,

I'm getting a lot of this errors in deamon log, any clue ?

2018-Jan-04 00:37:42.398832 INFO    [65.92.201.88:48772 OUT] Tx verification failed
2018-Jan-04 00:37:42.781303 INFO    [115.69.166.72:48772 OUT] Tx verification failed
2018-Jan-04 00:37:43.202647 INFO    [98.122.186.16:48772 OUT] Tx verification failed
2018-Jan-04 00:37:48.081607 INFO    [121.44.172.118:48772 OUT] Tx verification failed

**Comment by valiant1x** [comment]
These errors are generated by old clients on the network using previous versions of the software that are not compatible with the latest software. You can safely ignore them.
