### ISSUE TITLE
Tx verification failed v1.4.1

### ISSUE THREAD

**Issue by KhmerRun** [valiant1x/intensecoin#15]
Hello,

I wonder I always saw this message running daemons:

2018-Jan-09 04:23:38.174827 INFO    [54.37.72.35:48772 OUT] Tx verification failed
2018-Jan-09 04:23:38.178370 INFO    [75.190.146.8:48772 OUT] Tx verification failed
2018-Jan-09 04:23:38.579269 INFO    [75.190.146.8:48772 OUT] Tx verification failed
2018-Jan-09 04:23:38.981015 INFO    [173.70.221.196:48772 OUT] Tx verification failed
2018-Jan-09 04:23:38.984562 INFO    [173.70.221.196:48772 OUT] Tx verification failed
2018-Jan-09 04:23:38.987797 INFO    [188.80.86.241:48772 OUT] Tx verification failed
2018-Jan-09 04:23:39.389930 INFO    [188.80.86.241:48772 OUT] Tx verification failed
2018-Jan-09 04:23:39.393421 INFO    [92.141.88.224:48772 OUT] Tx verification failed
2018-Jan-09 04:23:39.794405 INFO    [92.141.88.224:48772 OUT] Tx verification failed
2018-Jan-09 04:23:40.195453 INFO    [173.48.34.110:48772 OUT] Tx verification failed
2018-Jan-09 04:23:40.198879 INFO    [173.48.34.110:48772 OUT] Tx verification failed
2018-Jan-09 04:23:40.600854 INFO    [85.191.252.43:48772 OUT] Tx verification failed
2018-Jan-09 04:23:40.604366 INFO    [85.191.252.43:48772 OUT] Tx verification failed

Regards,

**Comment by cryptogrot** [comment]
Same for me.

**Comment by cryptogrot** [comment]
So, these messages are related to people using and old client version.

**Comment by valiant1x** [comment]
@cryptogrot is exactly right, these messages are your daemon rejecting bad TXs from other clients. No need to worry.
