### ISSUE TITLE
1.4.1 error message: Illegal instruction

### ISSUE THREAD

**Issue by goodman3654** [valiant1x/intensecoin#18]
./intensecoind
Illegal instruction

CPU: E5-2680 v2
OS: Ubuntu 14.04. 

Can't start daemon, Can anyone help? Best regards.

**Comment by valiant1x** [comment]
your CPU is missing the necessary instructions for the cryptonote algorithm (AES) and possibly some code enhancements the software was compiled with (SSE). please try compiling from source to address the latter

**Comment by goodman3654** [comment]
But E5-2680 v2 is supported both AES and SSE. That's weird...

And I will try to compile from source to see if this error still exists.

**Comment by goodman3654** [comment]
tring to compile. but encountered error as below. 

Ubuntu 14.04
GCC 4.8.5
CMake 2.8.12.2
Boost 1.55.

root@test:~/intensecoin/intensecoin-1.4.1# make
mkdir -p build/release
cd build/release && cmake -D CMAKE_BUILD_TYPE=Release ../..
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- CXX COMPILER VERSION: 4.8

-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   chrono
--   regex
--   serialization
--   program_options
-- Found Git: /usr/bin/git (found version "1.9.1")
-- Performing Test HAVE_SSE42
-- Performing Test HAVE_SSE42 - Success
-- Performing Test HAVE_THREAD_LOCAL
-- Performing Test HAVE_THREAD_LOCAL - Success
-- Performing Test HAVE_OMIT_LEAF_FRAME_POINTER
-- Performing Test HAVE_OMIT_LEAF_FRAME_POINTER - Success
-- Performing Test HAVE_FALLOCATE
-- Performing Test HAVE_FALLOCATE - Failed
-- Looking for malloc_usable_size
-- Looking for malloc_usable_size - not found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindThreads.cmake:166 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  external/rocksdb/CMakeLists.txt:319 (find_package)


-- Configuring incomplete, errors occurred!
See also "/root/intensecoin/intensecoin-1.4.1/build/release/CMakeFiles/CMakeOutput.log".
See also "/root/intensecoin/intensecoin-1.4.1/build/release/CMakeFiles/CMakeError.log".
make: *** [cmake-release] Error 1

**Comment by valiant1x** [comment]
@goodman3654 please try building the latest version of cmake from source and use the newer version instead

**Comment by qskousen** [comment]
I had the same error on Ubuntu 16.04, building from latest source worked.
