### ISSUE TITLE
Compilation on Windows 10

### ISSUE THREAD

**Issue by luiscosio** [valiant1x/intensecoin#19]
First, I'm running: 

1. cmake.exe -DBOOST_ROOT=C:\boost_1_59_0 -DBOOST_LIBRARYDIR=C:\boost_1_59_0\libs\ -DQt5_DIR=D:\Qt\5.10.0\msvc2013_64\lib\cm
ake\Qt5 -G "Visual Studio 14 Win64" .
2. Open everything using Visual Studio 14
3. Build

Getting this error:

6>D:\Projects\intensecoinwallet\src\CryptoNoteWrapper\WalletGreenWorker.cpp(398): error C2039: 'resetPendingTransactions': is not a member of 'CryptoNote::WalletGreen'
6>  D:\Projects\intensecoinwallet\cryptonote\src\Wallet/WalletGreen.h(36): note: see declaration of 'CryptoNote::WalletGreen'
6>D:\Projects\intensecoinwallet\src\CryptoNoteWrapper\WalletGreenWorker.cpp(398): error C2039: '__this': is not a member of 'CryptoNote::WalletGreen'
6>  D:\Projects\intensecoinwallet\cryptonote\src\Wallet/WalletGreen.h(36): note: see declaration of 'CryptoNote::WalletGreen'

Any ideas?

**Comment by valiant1x** [comment]
this is a GUI (intensecoinwallet) build issue, not daemon, but it sounds like the `cryptonote` submodule is out of date. the easiest fix is likely just performing a `git pull` in the main intensecoinwallet dir. if that still doesn't work, run `git pull` in `/cryptonote/`

**Comment by luiscosio** [comment]
It worked. 

Thank you so much!
