### ISSUE TITLE
Daemon error

### ISSUE THREAD

**Issue by tranhoaison** [valiant1x/intensecoin#2]
when i run ./intensecoind on ~/intensecoin/src.
i got this error:
root@standanrd:~/intensecoin/src# ./intensecoind
2017-Sep-04 02:56:21.455029 INFO    intensecoin v2.1.0.1243 (0.1-gfba89377f)
2017-Sep-04 02:56:21.455284 INFO    Module folder: ./intensecoind
2017-Sep-04 02:56:21.455488 INFO    Opening DB in /root/.intensecoin/DB
2017-Sep-04 02:56:21.469235 INFO    DB opened in /root/.intensecoin/DB
2017-Sep-04 02:56:21.472546 INFO    Initializing core...
2017-Sep-04 02:56:21.476294 INFO    Core initialized OK
2017-Sep-04 02:56:21.476461 INFO    Initializing p2p server...
2017-Sep-04 02:56:21.477102 INFO    Binding on 0.0.0.0:48772
2017-Sep-04 02:56:21.477243 INFO    Net service binded on 0.0.0.0:48772
2017-Sep-04 02:56:21.477334 INFO    Attempting to add IGD port mapping.
2017-Sep-04 02:56:25.482376 INFO    No IGD was found.
2017-Sep-04 02:56:25.482645 INFO    P2p server initialized OK
2017-Sep-04 02:56:25.483326 INFO    Starting core rpc server on address 127.0.0.                                                                                        1:48782
2017-Sep-04 02:56:25.483491 INFO    Core rpc server started ok
2017-Sep-04 02:56:25.483605 INFO    Starting p2p net loop...
2017-Sep-04 02:56:25.483705 INFO    Starting node_server
2017-Sep-04 02:56:36.119021 INFO    [197.89.147.121:48772 OUT] Sync data returned unknown top block: 12666 -> 12675 [9 blocks (0 days) behind]
2017-Sep-04 02:56:36.119021 INFO    SYNCHRONIZATION started
2017-Sep-04 02:56:37.494084 INFO    [197.89.147.121:48772 OUT] SYNCHRONIZED OK
2017-Sep-04 02:56:37.494336 INFO
2017-Sep-04 02:56:37.494336 INFO    **********************************************************************
2017-Sep-04 02:56:37.494336 INFO    You are now synchronized with the network. You may now start simplewallet.
2017-Sep-04 02:56:37.494336 INFO
2017-Sep-04 02:56:37.494336 INFO    Please note, that the blockchain will be saved only after you quit the daemon with "exit" command or if you use "save" command.
2017-Sep-04 02:56:37.494336 INFO    Otherwise, you will possibly need to synchronize the blockchain again.
2017-Sep-04 02:56:37.494336 INFO
2017-Sep-04 02:56:37.494336 INFO    Use "help" command to see the list of available commands.
2017-Sep-04 02:56:37.494336 INFO    **********************************************************************
2017-Sep-04 02:56:40.857126 WARNING Transaction 78896d5bec8e6a6b2f3235666ff1e3167308e877ded0c42e5346d51b7df62961 is not valid. Reason: fee is too small and it's not a fusion transaction
2017-Sep-04 02:56:40.857483 INFO    [197.89.147.121:48772 OUT] Tx verification failed
2017-Sep-04 02:56:41.011156 WARNING Transaction 90c8cee2ab72cb7db2a294100dbdfe00362f30f1d19b92a86b805c3da2030dd8 is not valid. Reason: fee is too small and it's not a fusion transaction
2017-Sep-04 02:56:41.011530 INFO    [197.89.147.121:48772 OUT] Tx verification failed
2017-Sep-04 02:56:41.175969 WARNING Transaction f0b9fdd0204b039ceca53e5d3fa22c01f41a0adc4d2d215cdf4a1477ee668865 is not valid. Reason: fee is too small and it's not a fusion transaction
2017-Sep-04 02:56:41.177781 INFO    [197.89.147.121:48772 OUT] Tx verification failed
2017-Sep-04 02:56:41.517432 WARNING Transaction b1d0bf61f9ab534dc8e1e3d48de784ced615be218dc6d363c7539efd4e8a74a0 is not valid. Reason: fee is too small and it's not a fusion transaction
2017-Sep-04 02:56:41.517720 INFO    [197.89.147.121:48772 OUT] Tx verification failed
2017-Sep-04 02:56:41.667017 WARNING Transaction 3e74d2eedf413e67db9fd6d3b004b724bbb1487f7a9cfd08b814dbede706d1c5 is not valid. Reason: fee is too small and it's not a fusion transaction
2017-Sep-04 02:56:41.667298 INFO    [197.89.147.121:48772 OUT] Tx verification failed
2017-Sep-04 02:56:41.822251 WARNING Transaction c5eedacd94a07cf3fcb658ec81cc30dbb3cfc6ca7139957b8d6d108611fe4d1d is not valid. Reason: fee is too small and it's not a fusion transaction
2017-Sep-04 02:56:41.822544 INFO    [197.89.147.121:48772 OUT] Tx verification failed
2017-Sep-04 02:56:41.973206 WARNING Transaction c7a2852c49ed8c3626faa8f08e01271f0d001bf6fad72ffe2ad4a03b4b9570c7 is not valid. Reason: fee is too small and it's not a fusion transaction
2017-Sep-04 02:56:41.973509 INFO    [197.89.147.121:48772 OUT] Tx verification failed
2017-Sep-04 02:56:42.124303 WARNING Transaction 339caba2e2e45f16ff0feedb0416d2de160527028e27293faacdc615381acb6f is not valid. Reason: fee is too small and it's not a fusion transaction
2017-Sep-04 02:56:42.124675 INFO    [197.89.147.121:48772 OUT] Tx verification failed

**Comment by valiant1x** [comment]
Hi,

Apologies for the late response, did not see the issue open.

You can disregard those errors. The errors represent your client rejecting other clients' transactions. I am not sure why people are sending 0 fee transactions, but there is a minimum fee on the network. Your daemon is simply warning you that those 0 fee transactions are being rejected. Nothing to worry about.
