### ISSUE TITLE
Lost coins in pool

### ISSUE THREAD

**Issue by droidcoinio** [valiant1x/intensecoin#21]
Hi, all

I am an ITNS pool manager. Last 24 hours, my pool found 20 blocks. However, I found that the pool wallet didn't have enough coins to payout. I had to send my own coins to the pool. I am not sure what really happened.
1) We found an orphan block (105201). Should the pool pay any coins to the miner? How to avoid orphan block? 
2) I set the payment in config.json as follows:
    "payments": {
        "enabled": true,
        "interval": 600,
        "maxAddresses": 5000,
        "mixin": 1,
        "transferFee": 500000,
        "minPayment": 100000000,
        "maxTransactionAmount": 0,
        "denomination": 10000000
    },
Maybe I should change the transferFee to 50000, and set the minPayment to 10000000?

Any suggestions are appreciated!

**Comment by valiant1x** [comment]
If you are paying out blocks before the maturation time set by the network (60 blocks) this is the most likely culprit.. make sure depth is set to 60

Also try `reset`ing the wallet to ensure it isn't just out of sync
