### ISSUE TITLE
Simplewallet won't start

### ISSUE THREAD

**Issue by screab-idh** [valiant1x/intensecoin#22]
Hi,

I am trying to generate a wallet with sources compiled on ubuntu 16.04 and this is what I get every time:

2018-Jan-16 11:04:29.945779 ERROR   Error: failed to save new wallet: locale::facet::_S_create_c_locale name not valid
2018-Jan-16 11:04:29.946625 ERROR   Error: failed to generate new wallet: locale::facet::_S_create_c_locale name not valid
2018-Jan-16 11:04:29.946663 ERROR   account creation failed
2018-Jan-16 11:04:29.946690 ERROR   Failed to initialize wallet
2018-Jan-16 11:04:43.831679 ERROR   Error: wallet failed to connect to daemon (http://localhost:48782).

Any ideas as to why this might happen ? 

p.s. the daemon seems to work just fine and it is listening on the correct port.

**Comment by valiant1x** [comment]
see https://github.com/valiant1x/intensecoin/issues/9

**Comment by screab-idh** [comment]
It worked, thanks.
