### ISSUE TITLE
BlockchainSynchronizer failed to query blocks

### ISSUE THREAD

**Issue by screab-idh** [valiant1x/intensecoin#23]
Hello,

I started the wallet and I get this error every minute:

2018-Jan-17 13:19:46.373244 ERROR   [BlockchainSynchronizer] Failed to query blocks: NodeErrorCategory:3, Network error

Can you explain to me what this means and what (if anything) should I do to fix it ?

**Comment by cryptogrot** [comment]
Did you try to restart the sync ? Maybe a network connectivity issue.
