### ISSUE TITLE
intensecoind RPC getblockheight returns wrong block

### ISSUE THREAD

**Issue by CoinLogik** [valiant1x/intensecoin#24]
I call `getblockheight` asking for block at height 90 and it returns block at height 89:
```
getblockheight(90) ->
    returns
        height 89 (??)
        hash 74011bffa6b6e091257bdadf5e3ca8d669daa153fe77ca7168d7935c5b656e69
```

Meanwhile, getlastblockheader shows the true block at height 90
```
getlastblockheader ->
    returns
        height 90
        hash 40608830e177c1bcb6fec91769cc00544cf980f50e2f03319d84928bc02d1e7b
```

Compare with Monero, which returns the same height block for which you request:

```
curl node.xmrbackb.one:18081/json_rpc -d '{"method":"getblockheaderbyheight", "params": { "height": 1489569}}'
```

Returns block 1489569:
```
{
  "id": 0,
  "jsonrpc": "2.0",
  "result": {
    "block_header": {
...
      "hash": "28a3421c281ae49d275f9045ea32d8b4265e12358e082bb3002083a6cec3e713",
      "height": 1489569,
...
    },
    "status": "OK"
  }
```

**Comment by valiant1x** [comment]
It's a BCN aesthetic nuance. For whatever reason they chose to visually increment most blocks by 1 (using a 1-based index on the outside) but internally it still uses a 0-based index. Monero correctly uses a 0-based index everywhere.

**Comment by CoinLogik** [comment]
It's a shame - pretty much ensures to confuse devs dealing with the RPCs and cause bugs in pool software, block explorers, etc.
