### ISSUE TITLE
I want to setup pool

### ISSUE THREAD

**Issue by mk148a** [valiant1x/intensecoin#3]
Hi, i want to setup pool. And i how how to setup aeon/xmr pool. But its little different, what is the connectivity tool? how much ram needed for this and  can i use aeon+intense pool on one server?

**Comment by valiant1x** [comment]
Hello, you do not need to use the connectivity tool to setup a pool. You can run as many pools as you want on one server as long as your pool configs are setup for different ports. In terms of RAM you will likely need at least 1GB to run the daemon and a node-based pool. You can always set-up a swap partition if you are having memory issues.
