### ISSUE TITLE
1.4.2 on Ubuntu16.04 shows Tx verification failed

### ISSUE THREAD

**Issue by goodman3654** [valiant1x/intensecoin#30]
I compiled 1.4.2 and run on Ubuntu16.04, after synced blockchan data, it shows lots of messages like below, is it normal or there is something wrong?

2018-Jan-25 23:10:08.340674 INFO    [174.109.170.49:48772 OUT] Tx verification failed
2018-Jan-25 23:10:08.349064 INFO    [182.156.212.3:48772 OUT] Tx verification failed
2018-Jan-25 23:10:08.358042 INFO    [77.244.2.4:48772 OUT] Tx verification failed
2018-Jan-25 23:10:08.397483 INFO    [89.35.173.254:48772 OUT] Tx verification failed
2018-Jan-25 23:10:08.524428 INFO    [14.49.87.11:48772 OUT] Tx verification failed
2018-Jan-25 23:13:10.917567 INFO    [35.205.108.96:48772 OUT] Tx verification failed
2018-Jan-25 23:13:10.950819 INFO    [14.49.87.11:48772 OUT] Tx verification failed
2018-Jan-25 23:13:10.958921 INFO    [54.38.38.197:48772 OUT] Tx verification failed
2018-Jan-25 23:13:10.965821 INFO    [182.156.212.3:48772 OUT] Tx verification failed
2018-Jan-25 23:13:10.976397 INFO    [77.244.2.4:48772 OUT] Tx verification failed
2018-Jan-25 23:13:10.991445 INFO    [89.35.173.254:48772 OUT] Tx verification failed
2018-Jan-25 23:13:11.836038 INFO    [174.109.170.49:48772 OUT] Tx verification failed
2018-Jan-25 23:14:59.278404 INFO    [14.49.87.11:48772 OUT] Tx verification failed
2018-Jan-25 23:14:59.351692 INFO    [89.35.173.254:48772 OUT] Tx verification failed
2018-Jan-25 23:14:59.414461 INFO    [94.130.228.153:48772 OUT] Tx verification failed
2018-Jan-25 23:14:59.606045 INFO    [54.38.38.197:48772 OUT] Tx verification failed
2018-Jan-25 23:15:00.320383 INFO    [182.156.212.3:48772 OUT] Tx verification failed
2018-Jan-25 23:15:00.395779 INFO    [174.109.170.49:48772 OUT] Tx verification failed
2018-Jan-25 23:15:00.670048 INFO    [77.244.2.4:48772 OUT] Tx verification failed

**Comment by valiant1x** [comment]
not an issue, see https://github.com/valiant1x/intensecoin/issues/12 https://github.com/valiant1x/intensecoin/issues/15
