### ISSUE TITLE
[BlockchainSynchronizer] Failed to query outdated pool transaction: NodeErrorCa tegory:3, Network error

### ISSUE THREAD

**Issue by schmeckles22** [valiant1x/intensecoin#31]
Hello,

I claim to be no expert and I am doing this just for learning purposes.

I have setup intensecoind and the blockchain has updated, redis-server is running and when I try start simplewallet I get the following error.

[BlockchainSynchronizer] Failed to query outdated pool transaction: NodeErrorCa tegory:3, Network error

On the intensecoind
018-Jan-28 16:22:09.155628 WARNING [127.0.0.1:43785 INC] Exception in connectionHandler: Levin signature mismatch

simplewallet --wallet-file ./Easy-ITNS --password ********* --rpc- bind-ip 0.0.0.0 --rpc-bind-port 8554 --daemon-port 48772

Thank you and I appreciate your help :)

**Comment by valiant1x** [comment]
you need to connect to the daemon RPC port (48782), not P2P port

**Comment by schmeckles22** [comment]
@valiant1x I will give that a shot now, I thought the wallet created its own RPC and not connecting to the daemon... silly me.
