### ISSUE TITLE
Intensecoin wallet v.1.4.21 issue

### ISSUE THREAD

**Issue by Bepeck-kun** [valiant1x/intensecoin#32]
Hello. I have downloaded Intensecoin wallet v.1.4.21, create a wallet and got a wierd problems:
1. deamon doesn't connect to chain (C:\ProgramData\intensecoin\lmdb 76.0 KB (77,824))
sync_info
Height: 1, target: 1 (100%)
Downloading at 0 kB/s
3 peers
111.231.72.116:48772      0000000000000000  0  0 kB/s, 0 blocks / 0 MB queued
104.200.65.202:48772      0000000000000000  0  0 kB/s, 0 blocks / 0 MB queued
62.48.164.61:48772        0000000000000000  0  0 kB/s, 0 blocks / 0 MB queued
0 spans, 0 MB

2. all other wallet version (1.4.1, GUI version and CLI version from off.site) doesn't accept any *.key or wallet file from v.1.4.2 because seems that password is incorrect, even it is empty.

3. Pre-release 1.4.3 opens wallet file, but still doesn't upload the chain. With manually import blockchain.raw file i see a zero balance.

**Comment by valiant1x** [comment]
1  and 3 appear to be the same issue - please run the daemon with `--log-level 3` and upload the output here

For issue 2, there is a known compatibility issue with pre-1.4.3 wallets and 1.4.3 or later.

**Comment by Bepeck-kun** [comment]
here is the output from deamon. [intensecoind.log](https://github.com/valiant1x/intensecoin/files/1691585/intensecoind.log)
for issue 2 - i have a 1.4.2 wallet version, if it's not compatible with previous versions too -  i just need a deamon working correctly for gain all transactions.

**Comment by valiant1x** [comment]
should be resolved by df7159c. [Windows release](https://github.com/valiant1x/intensecoin/releases/tag/1.4.3) was updated, please test and let me know if issues persist

**Comment by Bepeck-kun** [comment]
**********************************************************************
You are now synchronized with the network. You may now start intense-wallet-cli.
Use the "help" command to see the list of available commands.
[wallet iz4KVd]:
Refresh done, blocks received: 0
Balance: 0.00000000, unlocked balance: 0.00000000

**Comment by valiant1x** [comment]
are you certain it's the correct wallet address (command `address` in the wallet cli)?

mind that the only way to import wallets from pre-1.4.3 in 1.4.3 or later, is manually exporting secret keys from pre-1.4.3 and manually importing them in to 1.4.3. did you do that? also try using the command `rescan_bc` in the wallet.

**Comment by valiant1x** [comment]
to resolve your issue, restore your wallet (create a new one) using the word seed or the private keys. the wallet you referenced was created in 1.44.0 or earlier, which had a bug that caused wallets generated while the daemon was offline to have too high of a height it began scanning the blockchain for txs.
