### ISSUE TITLE
Daemon - Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by BKdilse** [valiant1x/intensecoin#38]
Can anyone help on the intensecoind dying with a "Segmentation fault (core dumped)" error?

I am testing out a nodejs-pool build (https://github.com/Snipa22/nodejs-pool), and all works fine, until I start the blockManager, which kills the daemon.

The packages I have may be incorrect:
    "forknote-util": "git+https://github.com/wallet42/node-forknote-util.git",
    "cryptonote-util": "git+https://github.com/Snipa22/node-cryptonote-util.git#xmr-Nan-2.0",
    "multi-hashing": "git+https://github.com/Snipa22/node-multi-hashing-aesni.git"

I don't have a working set of instructions, so am really doing this on trial and error.

**Comment by BKdilse** [comment]
looks like I need the correct itns.js coin files.

Anyone have this working, and could share the files?

**Comment by valiant1x** [comment]
please use [Venthos' nodejs-pool repo](https://github.com/Venthos/nodejs-pool) which was created for ITNS and is actively supported
