### ISSUE TITLE
Sent balance not deducted after update

### ISSUE THREAD

**Issue by KhmerRun** [valiant1x/intensecoin#39]
Hello,

I just re-compile intense again today by cloning from github. After blockchain synced, I created new wallet from --generate-from-view-key option. After the new imported wallet re-sync with blockchain, I have seen the balance only "received" and there is no sent balance out. It meant that the balance of my new wallet created from viewkey is more than it supposed to be.

Regards,

**Comment by valiant1x** [comment]
Sounds like there may have been a typo or other issue in importing the secret spend key. What is your source for the imported secret keys?

**Comment by valiant1x** [comment]
The reason you are seeing this behavior is you used the generate from view
key command. Wallets generated from view keys only show incoming
transactions and no outgoing or spend transactions. Use the argument
generate-from-keys instead, which will also prompt for a spend key.

**Comment by KhmerRun** [comment]
How to get spend key, during my wallet creation using simplewallet before, it doesn't show spendkey, only view key. For your info, I still can access to my old wallet file with password.

./simplewallet
2018-Jan-23 19:11:09.489341 INFO    intensecoin wallet v1.4.1.1 (0.1--g)
Nor 'generate-new-wallet' neither 'wallet-file' argument was specified.
What do you want to do?
[O]pen existing wallet, [G]enerate new wallet file or [E]xit.
G
Specify wallet file name (e.g., wallet.bin).
Wallet file name: OLDWALLET
password: ****************
2018-Jan-23 19:12:24.068944 INFO    Generated new wallet: XXXXXXXXXX
2018-Jan-23 19:12:24.068944 INFO    view key: XXXXXXXX
2018-Jan-23 19:12:24.069123 INFO    **********************************************************************
Your wallet has been generated.
Use "help" command to see the list of available commands.
Always use "exit" command when closing simplewallet to save
current session's state. Otherwise, you will possibly need to synchronize
your wallet again. Your wallet key is NOT under risk anyway.
