### ISSUE TITLE
daemon hangs when LMDB mapsize needs to be increased

### ISSUE THREAD

**Issue by mtl1979** [valiant1x/intensecoin#43]
When LMDB mapsize needs to be increased in middle of sync, daemon hangs with high CPU and memory usage. Killing the daemon and restarting will immediately increase the LMDB mapsize and resume syncing.

**Comment by iedemam** [comment]
Thanks for the report!

Looks like it's been seen in this upstream issue: https://github.com/monero-project/monero/issues/3230
and fixed with this pull request: https://github.com/monero-project/monero/pull/3231
