### ISSUE TITLE
ANONYMITY LEVEl can exceed apparent maximum

### ISSUE THREAD

**Issue by quantumproducer** [valiant1x/intensecoin#47]
50 is the max if you drag the bar.
Clicking the up arrows or typing you can enter any value

<img width="222" alt="screen shot 2018-03-17 at 12 14 16" src="https://user-images.githubusercontent.com/11827932/37557560-bd79885a-29dc-11e8-860a-7e0ff3228779.png">

**Comment by valiant1x** [comment]
this is a [GUI bug](https://github.com/valiant1x/intensecoinwallet) in an obsolete version of the GUI; please consider switching to the beta release.
