### ISSUE TITLE
master is not compiling

### ISSUE THREAD

**Issue by podvodnik** [valiant1x/intensecoin#49]
when compiling master I get following misstakes:

/home/x/intensecoin/tests/core_tests/block_validation.cpp: In function ‘bool {anonymous}::lift_up_difficulty(std::vector<boost::variant<cryptonote::block, cryptonote::transaction, cryptonote::account_base, callback_entry, serialized_object<cryptonote::block>, serialized_object<cryptonote::transaction>, event_visitor_settings> >&, std::vector<long unsigned int>&, std::vector<long unsigned int>&, test_generator&, size_t, cryptonote::block, const cryptonote::account_base&)’:
/home/x/intensecoin/tests/core_tests/block_validation.cpp:48:105: error: cannot convert ‘std::vector<long unsigned int>’ to ‘uint8_t {aka unsigned char}’ for argument ‘1’ to ‘cryptonote::difficulty_type cryptonote::next_difficulty(uint8_t, std::vector<long unsigned int>, std::vector<long unsigned int>)’
       difficulty_type diffic = next_difficulty(timestamps, cummulative_difficulties,DIFFICULTY_TARGET_V1);
                                                                                                         ^
/home/x/intensecoin/tests/core_tests/block_validation.cpp: In member function ‘bool gen_block_invalid_nonce::generate(std::vector<boost::variant<cryptonote::block, cryptonote::transaction, cryptonote::account_base, callback_entry, serialized_object<cryptonote::block>, serialized_object<cryptonote::transaction>, event_visitor_settings> >&) const’:
/home/x/intensecoin/tests/core_tests/block_validation.cpp:178:101: error: cannot convert ‘std::vector<long unsigned int>’ to ‘uint8_t {aka unsigned char}’ for argument ‘1’ to ‘cryptonote::difficulty_type cryptonote::next_difficulty(uint8_t, std::vector<long unsigned int>, std::vector<long unsigned int>)’
   difficulty_type diffic = next_difficulty(timestamps, commulative_difficulties,DIFFICULTY_TARGET_V1);
                                                                                                     ^
/home/x/intensecoin/tests/core_tests/block_validation.cpp: In member function ‘bool gen_block_invalid_binary_format::generate(std::vector<boost::variant<cryptonote::block, cryptonote::transaction, cryptonote::account_base, callback_entry, serialized_object<cryptonote::block>, serialized_object<cryptonote::transaction>, event_visitor_settings> >&) const’:
/home/x/intensecoin/tests/core_tests/block_validation.cpp:575:87: error: cannot convert ‘std::vector<long unsigned int>’ to ‘uint8_t {aka unsigned char}’ for argument ‘1’ to ‘cryptonote::difficulty_type cryptonote::next_difficulty(uint8_t, std::vector<long unsigned int>, std::vector<long unsigned int>)’
     diffic = next_difficulty(timestamps, cummulative_difficulties,DIFFICULTY_TARGET_V1);
                                                                                       ^
/home/x/intensecoin/tests/core_tests/block_validation.cpp:590:85: error: cannot convert ‘std::vector<long unsigned int>’ to ‘uint8_t {aka unsigned char}’ for argument ‘1’ to ‘cryptonote::difficulty_type cryptonote::next_difficulty(uint8_t, std::vector<long unsigned int>, std::vector<long unsigned int>)’
   diffic = next_difficulty(timestamps, cummulative_difficulties,DIFFICULTY_TARGET_V1);
                                                                                     ^
tests/core_tests/CMakeFiles/coretests.dir/build.make:86: recipe for target 'tests/core_tests/CMakeFiles/coretests.dir/block_validation.cpp.o' failed
make[3]: *** [tests/core_tests/CMakeFiles/coretests.dir/block_validation.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Entering directory '/home/x/intensecoin/build/release'
Scanning dependencies of target cold-outputs_fuzz_tests
make[3]: Leaving directory '/home/x/intensecoin/build/release'
make[3]: Entering directory '/home/x/intensecoin/build/release'
[ 59%] Building CXX object tests/fuzz/CMakeFiles/cold-outputs_fuzz_tests.dir/cold-outputs.cpp.o
make[3]: Leaving directory '/home/x/intensecoin/build/release'
CMakeFiles/Makefile2:2157: recipe for target 'tests/core_tests/CMakeFiles/coretests.dir/all' failed
make[2]: *** [tests/core_tests/CMakeFiles/coretests.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 59%] Building CXX object tests/fuzz/CMakeFiles/cold-outputs_fuzz_tests.dir/fuzzer.cpp.o
[ 60%] Linking CXX executable cold-outputs_fuzz_tests
make[3]: Leaving directory '/home/x/intensecoin/build/release'
[ 60%] Built target cold-outputs_fuzz_tests
make[2]: Leaving directory '/home/x/intensecoin/build/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/x/intensecoin/build/release'
Makefile:62: recipe for target 'release-all' failed
make: *** [release-all] Error 2

**Comment by Venthos** [comment]
This is the same as Issue #37 which is being fixed through Pull Request #44.  It should get fixed shortly.  Until then, simply build with `make release` instead of `make` to skip building tests.

Although technically at that point you have experienced that error, you have already compiled the tools successfully and can start using them.

**Comment by podvodnik** [comment]
Do I understand it correctly that there is still problems with syncing blockchain on new master and problems with payments? Our pool runs on the old one forknote based version, does it make any sense to switch now to the new version?

**Comment by mtl1979** [comment]
Syncing works on master now... There was two separate issues that needed to be fixed....
