### ISSUE TITLE
New difficulty algorithm

### ISSUE THREAD

**Issue by zawy12** [valiant1x/intensecoin#53]
If you're still using my old Zawy v1b difficulty algorithm, you should upgrade to [LWMA](https://github.com/zawy12/difficulty-algorithms/issues/3).  Five Monero/Cryptonote coins are using it now ([here's their charts](https://github.com/zawy12/difficulty-algorithms/issues/23)) and about 6 more coin are about to fork to use it.  

Are you using N=17 block for zawy v1b?

**Comment by valiant1x** [comment]
Thanks very much for reaching out. We are utilizing [Sumokoin's current algorithm](https://github.com/sumoprojects/sumokoin/commit/00ff7ed8b5bca488c50a7d7384a154b28429ea42#diff-50a23da614857b207ded42826dcfa766) which relies upon median timestamps of the last 17 blocks. It could be improved and seems to have a bit more 'lag' on adjustment than would be ideal.

We will begin testing LWHM soon. It looks like Monero already has a PR for this https://github.com/monero-project/monero/pull/2887 - is the PR current with your current proposition? It's a bit challenging to follow changes across the long conversations in Github issues.

**Comment by zawy12** [comment]
I helped Sumokoin with that after they saw Karbowanec was using my N=17 SMA.  I now know N=17 was too small.  N=30 would have been a lot better, if not N=40.  LWMA is a lot better than the SMA.  I said "LWHM", but I meant LWMA.  No, the PR is not my current proposition.  It's almost as good.  That PR comes from Masari who's code is on the LWMA page.    Yes, I end up writing way too much on github issues when I was trying to figure things out.    I've tried to condense my learned knowledge that occurs in all that "issue pollution" at Zcash, Sumo, and Karbo into the "still-long-but mostly-correct" 21 issues in my repository.

**Comment by valiant1x** [comment]
Adopted zawy12's LWMA in 98cfc5f1bb37c6e4401dbd81635d9c24dde88b7f
Mainnet is using the new difficulty algorithm now. It was rolled into our v4 hard fork. It seems to be performing well. We will get a sense for response to hash attacks as the network continues to build hash rate after the fork.
