### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by CoFix** [valiant1x/intensecoin#59]
Hi Staff,

I am getting install error. 

../../src/cryptonote_basic/libcryptonote_basic.a(cryptonote_format_utils.cpp.o): In function `cryptonote::generate_genesis_block(cryptonote::block&)':
cryptonote_format_utils.cpp:(.text+0x7d8c): undefined reference to `cryptonote::construct_miner_tx(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, cryptonote::account_public_address const&, cryptonote::transaction&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned char)'
collect2: error: ld returned 1 exit status
tests/fuzz/CMakeFiles/block_fuzz_tests.dir/build.make:147: recipe for target 'tests/fuzz/block_fuzz_tests' failed
make[3]: *** [tests/fuzz/block_fuzz_tests] Error 1
make[3]: Leaving directory '/home/itns/intensecoin/build/release'
CMakeFiles/Makefile2:2326: recipe for target 'tests/fuzz/CMakeFiles/block_fuzz_tests.dir/all' failed
make[2]: *** [tests/fuzz/CMakeFiles/block_fuzz_tests.dir/all] Error 2
make[2]: Leaving directory '/home/itns/intensecoin/build/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/itns/intensecoin/build/release'
Makefile:62: recipe for target 'release-all' failed
make: *** [release-all] Error 2

How can i fix it?

**Comment by valiant1x** [comment]
@CoFix run `make clean` then `make release`
