### ISSUE TITLE
Cant find Blocks

### ISSUE THREAD

**Issue by ICOBOXER** [valiant1x/intensecoin#6]
Cant just be bad luck...

Our Pool
 Hash Rate: 7.42 KH/sec
 Block Found: about 17 hours ago
 Connected Miners: 3
 Total Pool Fee: 1%
 Block Found Every: 1 hour (est.)

Blcokchain says...

2017-Nov-14 01:17:01.237561 WARNING Transaction 19d3edcd84499665744e2b94f3d9221142b9e2d67e011c2d25cfa6cbd033a9fb is not valid. Reason: Transaction uses spent key image
2017-Nov-14 01:17:01.237625 INFO    [217.129.60.48:48772 OUT] Tx verification failed
2017-Nov-14 01:17:01.691054 INFO    [217.129.60.48:48772 OUT] Tx verification failed
2017-Nov-14 01:17:02.060275 INFO    [217.129.60.48:48772 OUT] Tx verification failed
2017-Nov-14 01:17:05.014334 INFO    [217.129.60.48:48772 OUT] Tx verification failed
2017-Nov-14 01:17:05.426975 INFO    [217.129.60.48:48772 OUT] Tx verification failed
2017-Nov-14 01:17:05.549046 INFO    [217.129.60.48:48772 OUT] Tx verification failed
2017-Nov-14 01:17:06.152384 INFO    [217.129.60.48:48772 OUT] Tx verification failed

**Comment by valiant1x** [comment]
Those messages are normal and indicate that your daemon is rejecting bad TXs from other people on the network. This is because some people are still using very old software that is not compliant with current network standards.

I would advise  monitoring `set_log 5` in the daemon so we can see low-level TRACE output and analyze for issues.

**Comment by valiant1x** [comment]
Checkout branch pre65kminingfix to address issues in block templates. It should not be necessary after block 65k.

**Comment by harjinder123** [comment]
2017-Nov-19 07:37:23.001599 INFO    [daemon] intensecoin v1.3.0.1 (0.1-master-g9df85e8)
2017-Nov-19 07:37:23.007599 INFO    [daemon] Module folder: D:\Intensecoin-daemon-win64\intensecoind.exe
2017-Nov-19 07:37:23.012600 INFO    [RocksDBWrapper] Opening DB in C:\Users\Win 7\AppData\Roaming/intensecoin/DB
2017-Nov-19 07:37:23.182609 INFO    [RocksDBWrapper] DB opened in C:\Users\Win 7\AppData\Roaming/intensecoin/DB
2017-Nov-19 07:37:23.190610 INFO    [daemon] Initializing core...
2017-Nov-19 07:37:23.202610 INFO    [Core] Importing blocks from blockchain storage
2017-Nov-19 07:37:23.207611 ERROR   [Core] Corrupted blockchain. Block with index 59652 and hash ecb54b18b6ef371d93db95dc967f4d84647e2b77e52a6bacd62a78a320376335 has previous block hash 9d98ceaa3b561a9c2423beb0a1872e149ff5c5baacdfcb6f55569e3b14c9dbd0, but parent has hash ecb54b18b6ef371d93db95dc967f4d84647e2b77e52a6bacd62a78a320376335. Resynchronize your daemon please.
2017-Nov-19 07:37:23.316617 INFO    [RocksDBWrapper] Closing DB.
2017-Nov-19 07:37:23.571632 ERROR   [daemon] Exception: Blockchain storage is corrupted

every time i start , it shows this msg  .
Intensecoin-daemon-win64

**Comment by valiant1x** [comment]
@harjinder123 please open a new issue for this problem, the issue you are responding to is unrelated. Regardless please clear your blockchain data from `%userprofile%\appdata\roaming\intensecoin` by deleting everything except .wallet files.
