### ISSUE TITLE
Getting Error Message and Unable to Sync the blocks

### ISSUE THREAD

**Issue by Prasanth619** [valiant1x/intensecoin#60]
Please help me with below error message... I'm keep getting this message... Please advise

[98.203.159.24:11897 OUT] sent wrong block: failed to parse and validate block:
040045aaec7312e7b85ae1c05408fbf4fe88ee44a72b85d9c9277f17596a0da84bfd010097c2a5d60545aaec7312e7b85ae1c05408fbf4fe88ee44a72b85d9c9277f17596a0da84bfd8cd10200010100000023032100a24280b42fc645a74a2079a30edf754ac383ed76711e061b3ddd98977199ede401d9ae1501ffb1ae15060102eb87270abf0d0c6a181d667b18df2ed7b3e63668fef4bc0111c9182a2e5c9ff41402d75e91fa351a3c3b7d5e5cde7dce9e153a250d774c8f016f4ff4ed28cbd9b427c80102099c7669c14c63fee2644e8e7e2e3fb8d6e7cdbc022e95ec83790a7d9310dc46d08603028df7d2197f9973232c02185af8eba79d525a19c74ca7538cd46af287fbca195fa0f73602a0a1327dc8c7b19770030cf74092e4e8f72b75286945f44f7d2d9f00e5ab5b7680897a02bdc3bb642bf881ed6722c438dd9d6193a162fb525936d07e08a81a4f658c6b742b01db6449146a051995398f26a99b633890c934782ce72a5f3030dc42b4676a5363020800000002059f142546a2a2bb6a81f85b550cf0464688d9ed5a574d74a5ba6c6da1cb7de96dd6d7c93b82b3f82fca90d167697e0557840aebe2b20ab2ca3a53ac689a42d49d2f5ba12523b884357a1f8f11d575358353925b5e6ed574fc1791e58f757d8bc2578c908eb45da6b5a2328e42baf36be97b5054ab340e114603f91a2030418189d48fbeb789fbd871ab800dee6bf3e0eba1e47ee0e05924af8d19e2c91f00bebd6c83b588614ef32963f8863057048703a64d03240e607c029d70d2ffca887cd2f7a5d7443f4c2de847005df443b060524d1e2f88fcad78ff9ec6648f42a6a6b765c67bb0bfe5c736a919dc20101350aadda3a1f7b92d2bcaa0eb353e6e47343702c7cb923532d64ae5c5678e2be69985b3b949fb1833ee28ef638c1d209cf127bd16dfbe5e62563324c01528d41fe7a4bae138658181b5a3f7c30d9bb447d4c2bafaf712078e531bbd256c1ad3bfa35460f2d29ed8ee513ce615fe27066632623e88ffaffc90a7710da52a92a10b35df1fc4815bf6d35c740f8418461a37523fb959f97b432827d80401503bf47ed30129981b3ddb4ca68c0072bb93606f2d7c67879b2fa56c42c5393af5d5dda280feef8f8061353fab02a09cb38b59b29cb635fa3411dda747c6e0cac34e36b70e8bef2f639d0d633ce469205131510da612c6db4a1fd668c6498bd81c2db66826da4693c7b6c3164755204bee16757bfd37af99ff374dcfb2f1d0431bf21db8bf51e1d00ffe36e12bf3bf20fdcd35a0711d0133827583e913995ff12376c520f7c5d8f32f08f026443027ee267b8525b26c224fef0a112600edd08457f2d7df07c169ac593d4fcbb6cbac0c429b7c3916d516f4dea3bf8fc31269369dac5378c716c67b82c3135110e34d5d2c61166b1bdd5c4825aafb5836d578881d081de120ec99663323ad1a751773e7cdc1d0d5cf319edb5f4fe1077490db89a6060f115bb5001048c35e9a74a9ab45fa7baa595baaf5312c775ef446ca2a4e362b623ca580fcd1e59f9932facdf2e8775c24162b62a81d8b35b9a52eaf301d211e92d713060b9c65efb28e95fd2faec8b9b3649e2bd27a3b0778efeebb03e2b1b2b35a3232e674c35ba48898f5df10a364e2142ea15e3e85622a14682c1c713139dc609e6bbe4527be4ef474ab00c86f2f591ef4f84884e4e3a034021599d12cd14fa810137b4262501e02d5cf3c3556a62b4f1912c295bb1aa01feda6b726515d107fed26596a922b068171290474a3e61700830e882d59c02f8c04a6e7477b1af2db438a831472b2a5c39b24d1092f9d0e5a0f11445693661081be52869bfb20730f7f24cd851d303af253b2d113b966d64caa3bd05749e4b2941dfa53460ee4a74c3735655f5b5eac2e9521f417dd8a5a48ea1712ca3b61b2a88f009870e3d3611d90561499aff37bf1b77befe4c9ffa6fcea7289081524ddb929deb7d17e46d3da640d366e7be3b75e4465e85594805e75e2474decf3bbff0ca31591ce4d254799452b0a117e9258b57c917f50776b505e32dbf01d69cc435175fb188ec90db58239fa9b5f6d064ae00aff0d133b987c8638163b0c7c27dd96c2a4ff6af6a2166df60f8414488d184cee8b8681266f9113aa0b5fa61de3e0a3fc282500b29087d4737f36fdfacf3380ea902edea57ed75726ed92dbfd1661eb8510167193f7841f45e697b39169771c028cfb96672d44ddd7653f957863a3954c1124ed06ec314dad0675c1bc8046aabb90bf60ff7a23b9e4d1aaaa88089cf2f9c7066f77100d669e0012854e090fef570addf017fb9f1a6ac305916dee424488d5e491d3438fa777d9407d826c9a07334757ae4147a8eaa8518b19ae7b74ccd2d1eb5c0dee7a033978baadb4c0e8ab7aa03c47ce78c49aa1aa875633d6022f0b673bfc38e3c67ef2b51ae6e345815f597e7b42bb6aadc401bc23a6018e1910e21a65f03833189ce6e5bb237c1275f107a860e4526d66d97acae92a8cc5e5df41671f99c972c84c14af27ceca3764d0c1da6fbad378c6b56e0e2fdadb35c1700fb9a825b068d7aee660f16f02057d5d6c9b398010ec412dde146942b1c240be90494adde04308e4314c7c015faa28940d2cc6a5c0e99f3e2a5ff60c802a46ba27fb82cbef7e24043af228efd94dc12d680c51a48c2e010446196c2e254da9e10bcc7b2b5149f2d62c4cb735118c1feb6b4ee46ae2d1bd62563536575c544f1eb1f5aa7124783109919c6ba6a7efecb5f1ece475129ef9922d0dee841c5282bb6e9887254dc3944618604368099e13567e05e23cba76d1620fb33b8c47af75750b9d8d011319bf267de13c9c5e3fc0c7ec2e5f1bf26d2e7bdf0aa3d905b83876f6fdf788e4590421081e884aa6c0885a0d8aa60a9aeaf868a96d9b1022d7d53da2320b64f75b9ef86f3d180de260b7a544458fa0532705a37bc1b2b4dd8c80e520abc0e25bb6e09335f94c963a68dd6f005d87b4ac4e35619fd19717d7529d6a43e92a01c6a5a626240b2a15ecc5d593b744b7c6aac3c7ff0a978baa06b491c3e4a4fd9d8a05f1138304946d70894654adc1eed99274795036bc4e33fefba79791fe0899d05ce5dbeb67cd1f50f770e8de1b9fc2d3af1337ba2f49823d964dbc3685600a0e0508c0b3938e6eeb4087ea2815fdbbba43d522c07c06962addafbceb508d042e479de24d812fe75a53f52d36a9b053d10237c56a4010a1dc1a2f5282f7cb8c41d9572de7003c3ee3c2fc4fafe4f5d10911bb1f6d367d660bf65a2fd03bbc68ea143a51d312832bb16ffd0add9d6d2b0895a9f33c3cb5ee62aa9cc969a9034af73f00f84200821d13919921c23ec278a4219b5dd767347b694903ad407eb08f99490e4145ea8f082114c07930a7fad52c323e592fb2d7d0e53015a9aef1985ae75ad67b999434efb5f3f9dce25c66ec850640a12d4ba0390b633348073808c665d54ea65e2a2ca4cdc519ef7c921d90f7237c601c0d68cf9e8e830203ecfecd2d9ae4118b235a3ff990070ae0f1f67d071794ad2273e9951cca1c5e10cf4c999e409e21206e172d6ff3e96b652f9b545ab1851efd620ae1dadf99287d607bde39443e569d5cf90a714c5f7cc72a2260b636185fe0e35754300afde859c7f555f7993e138b6c70aa9e31181a067760f3bf397187882139597831
 dropping connection

**Comment by valiant1x** [comment]
You might be running an old version of the rebase that was incompatible with some merged mining blocks. What is the output of `print_height` in the daemon?

**Comment by valiant1x** [comment]
Should be resolved in latest release (v2.0). If your issues persist please mention me and I'll reopen this.
