### ISSUE TITLE
Still having sync problems with intensecoin-gui-win64-v201

### ISSUE THREAD

**Issue by Staz1st** [valiant1x/intensecoin#87]
The wallet says it's syncing but blocks left gradually count upward. 

SYNCHRONIZATION started
2018-04-30 15:10:15.032 [P2P8]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:305     [62.48.164.60:48772 OUT] Sync data returned a new top block candidate: 173491 -> 173589 [Your node is 98 blocks (0 days) behind]
SYNCHRONIZATION started
2018-04-30 15:15:31.291 [P2P9]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:305     [62.48.164.60:48772 OUT] Sync data returned a new top block candidate: 173491 -> 173593 [Your node is 102 blocks (0 days) behind]
SYNCHRONIZATION started
sync_info
Height: 173491, target: 173593 (99.9412%)
Downloading at 31 kB/s
1 peers
62.48.164.60:48772        1d4bb33115dfb62e  173593  31 kB/s, 0 blocks / 0 MB queued
2 spans, 0.000147 MB
62.48.164.60:48772        100 (173490 - 173589)  -
                          1 (173567 - 173567, 0 kB)  0 kB/s (1)

**Comment by Staz1st** [comment]
using the exclusive nodes. Erased the blockchain and now it's rebuilding. Maybe this works

**Comment by Staz1st** [comment]
rebuild blockchain... same problem.
![syncerror2](https://user-images.githubusercontent.com/35668621/39444546-78e62dfc-4cb8-11e8-8019-4fee5c32d886.jpg)
[newnodes3t.txt](https://github.com/valiant1x/intensecoin/files/1961830/newnodes3t.txt)

More info if needed

**Comment by bobbyhabib** [comment]
Hi,

I have also been experiencing this issue on v2.0.1 both on gui and on v2.0.0 cmd line. It get to about block 173k block and just sits there. Also notice that the wallet synch jumps randomly saying there 7 days left and then 1 day and then back to 7 days. So the synchronisation of the blocks do not look sequential. Not sure if it suppose too but it might assist with your troubleshooting.

**Comment by Staz1st** [comment]
I resolved the problem finnaly by deleting the blockchain and rebiuld it from a snapshot. Up until now it looks stable.

**Comment by iedemam** [comment]
Thanks for the update. We're making some improvements for the next release to make this initial sync more reliable.
