### ISSUE TITLE
error when running wallet cli (simplewallet) at vps server

### ISSUE THREAD

**Issue by baliwae** [valiant1x/intensecoin#9]
when run at vps always error when close the wallet:
2017-Nov-25 14:13:38.142825 ERROR   Failed to store wallet: locale::facet::_S_create_c_locale name not valid

**Comment by valiant1x** [comment]
Please try installing the locales package, or enter `export LC_ALL=C.UTF-8` in the console

**Comment by baliwae** [comment]
it work! nice!
